### PR TITLE
Addition of load_count to board_alight.txt

### PR DESCRIPTION
**Pull request by hooversy**
This change seeks to include a field called `load_count` in `board_alight.txt`. The purpose of this field would be to provide an absolute ridership count. Currently, without knowing a starting zero and/or vehicle capacity, there are no fields in GTFS-ride that could contain this data either directly or in a calculated manner. The change is sought to be included in the January 2018 quarterly review.

### CODE REVIEW

**Comment by carletop** [comment]
`+1` This change should help avoid the situation where an agency has to leave out valuable data because it is not able to be converted to a specified format.

**Comment by portedav** [comment]
+1

**Comment by BenFields724** [comment]
+1

**Comment by jkkeck** [comment]
Would this be the balanced load that is adjusted so that each trip starts and ends with a zero? Could there be benefits of including an additional field identifying if the load_count field is balanced?  With a short, high-frequency transit circulator route (like at an airport), or at a synthetic terminal on an out-and-back loop trip where passengers are expected to board an outbound bus to travel inbound, the application of a balancing adjustment may not occur or be appropriate.

**Comment by hooversy** [comment]
@jkkeck This would be an absolute count of riders. A non-zero value at the start and end of a trip is possible and could indeed be expected in the examples you've mentioned. This change isn't addressing a balanced load value, but future changes could certainly look at such. Are there situations that you see where a balanced count value would provide information not obtainable from existing fields?

**Comment by hooversy** [comment]
With 3 `+1` votes and 0 `-1` votes, the change has been added to the Jan 2018 quarterly review.

**Comment by hooversy** [comment]
With 3 `+1` votes and 0 outstanding `-1` votes, the change has been added to the Jan 18 quarterly update.

**Pull request merged**
